
[project]
name = "dungeon-master"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.dungeon-master]
path = "contracts/dungeon-master.clar"
depends_on = []

[contracts.dme000-governance-token]
path = "contracts/dme000-governance-token.clar"
depends_on = []

[contracts.experience]
path = "contracts/experience.clar"
depends_on = []

[contracts.univ2-share-fee-to]
path = "contracts/univ2-share-fee-to.clar"
depends_on = []

[contracts.univ2-core]
path = "contracts/univ2-core.clar"
depends_on = []

[contracts.univ2-library]
path = "contracts/univ2-library.clar"
depends_on = []

[contracts.univ2-router]
path = "contracts/univ2-router.clar"
depends_on = []

[contracts.univ2-path2]
path = "contracts/univ2-path2.clar"
depends_on = []

[contracts.wstx]
path = "contracts/wstx.clar"
depends_on = []

[contracts.welshcorgicoin-token]
path = "contracts/welshcorgicoin-token.clar"
depends_on = []

[contracts.happy-welsh]
path = "contracts/happy-welsh.clar"
depends_on = []

[contracts.weird-welsh]
path = "contracts/weird-welsh.clar"
depends_on = []

[contracts.welsh-punk]
path = "contracts/welsh-punk.clar"
depends_on = []

[contracts.energetic-welsh]
path = "contracts/energetic-welsh.clar"
depends_on = []

[contracts.status-effects]
path = "contracts/status-effects.clar"
depends_on = []

[contracts.odins-raven]
path = "contracts/odins-raven.clar"
depends_on = []

[contracts.memobots-guardians-of-the-gigaverse]
path = "contracts/memobots-guardians-of-the-gigaverse.clar"
depends_on = []

[contracts.charisma-claims]
path = "contracts/charisma-claims.clar"
depends_on = []

[contracts.red-pill-nft]
path = "contracts/red-pill-nft.clar"
depends_on = []

[contracts.blue-pill-nft]
path = "contracts/blue-pill-nft.clar"
depends_on = []

[contracts.charisma-token]
path = "contracts/charisma-token.clar"
depends_on = []

[contracts.energy]
path = "contracts/energy.clar"
depends_on = []

[contracts.arcana]
path = "contracts/arcana.clar"
depends_on = []

[contracts.aura]
path = "contracts/aura.clar"
depends_on = []

[contracts.meme-engine-manager]
path = "contracts/meme-engines/meme-engine-manager.clar"
depends_on = []

[contracts.raven-wisdom]
path = "contracts/raven-wisdom.clar"
depends_on = []

[contracts.memobot-capacity]
path = "contracts/memobot-capacity.clar"
depends_on = []

[contracts.meme-engine]
path = "contracts/meme-engines/meme-engine.clar"
depends_on = []

[contracts.dungeon-keeper]
path = "contracts/dungeon-keeper.clar"
depends_on = []

[contracts.charisma-randomizer]
path = "contracts/charisma-randomizer.clar"
depends_on = []

# [contracts.fate-randomizer]
# path = "contracts/interactions/fate-randomizer.clar"
# depends_on = []

[contracts.fatigue]
path = "contracts/interactions/fatigue.clar"
depends_on = []

[contracts.keepers-petition]
path = "contracts/interactions/keepers-petition.clar"
depends_on = []

# [contracts.challenge]
# path = "contracts/interactions/challenge.clar"
# depends_on = []

[contracts.charisma-mine]
path = "contracts/interactions/charisma-mine.clar"
depends_on = []

[contracts.the-troll-toll]
path = "contracts/interactions/the-troll-toll.clar"
depends_on = []

[contracts.charismatic-corgi]
path = "contracts/interactions/charismatic-corgi.clar"
depends_on = []

[contracts.dungeon-crawler]
path = "contracts/dungeon-crawler.clar"
depends_on = []


# traits
[contracts.dao-traits-v4]
path = "contracts/dao-traits-v4.clar"
depends_on = []

[contracts.dao-traits-v7]
path = "contracts/dao-traits-v7.clar"
depends_on = []

[contracts.dao-traits-v8]
path = "contracts/dao-traits-v8.clar"
depends_on = []

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
